msats:
  ACCS: Access
  ACRE: ACRE
  ALLW: Alleyway
  ALWY: Alleyway
  AMBL: Amble
  ANCG: Anchorage
  APP: Approach
  ARC: Arcade
  ART: Artery
  ARTL: ARTL
  ARTY: ARTY
  AV: AV
  AVE: Avenue
  BA: BA
  BANK: BANK
  BASN: Basin
  BCH: Beach
  BDGE: Bridge
  BDWY: Broadway
  BEND: Bende
  BLK: Blank
  BOWL: Bowl
  BRAE: Brae
  BRAN: Branch
  BRCE: Brace
  BRET: Bret
  BRK: Break
  BROW: Brow
  BVD: Boulevard
  BVDE: Boulevard
  BWK: BWK
  BYPA: Bypass
  BYWY: Byway
  CAUS: Causeway
  CCT: Circuit
  CDS: Cul-De-Sac
  CH: Chase
  CIR: Circle
  CL: Close
  CLDE: Colonnade
  CLR: CLR
  CLT: Circlet
  CMMN: Common
  CNCD: CNCD
  CNN: CNN
  CNR: Corner
  CNWY: Centreway
  CON: Concourse
  COVE: Cove
  COWY: Crossway
  CPS: Copse
  CRD: Crossroad
  CRES: Crescent
  CRF: CRF
  CRK: CRK
  CRSE: Course
  CRSG: Crossing
  CRSS: Cross
  CRST: Crest
  CSO: Corso
  CT: Court
  CTR: Centre
  CTTG: Cutting
  CTYD: Courtyard
  CUT: CUT
  CUWY: Cruiseway
  DALE: Dale
  DASH: DASH
  DELL: Dell
  DENE: DENE
  DEVN: Deviation
  DIP: Dip
  DIV: DIV
  DOCK: DOCK
  DOM: DOM
  DOWN: DOWN
  DR: Drive
  DRWY: Driveway
  DSTR: Distributor
  DWNS: DWNS
  EDGE: Edge
  ELB: Elbow
  END: End
  ENT: Entrance
  ESMT: ESMT
  ESP: Esplanade
  EST: Estate
  EXP: Expressway
  EXTN: Extension
  FAWY: Fairway
  FBRK: FBRK
  FITR: Firetrail
  FK: FK
  FLAT: Flat
  FLNE: FLNE
  FLTS: FLTS
  FOLW: Follow
  FORD: FORD
  FORM: Formation
  FRNT: Front
  FRTG: Frontage
  FSHR: Foreshore
  FTRK: Fire Track
  FTWY: Footway
  FWY: Freeway
  GAP: Gap
  GDN: Garden
  GDNS: Gardens
  GLD: Glade
  GLEN: Glen
  GLY: Gully
  GR: Grove
  GRA: Grange
  GRN: Green
  GRND: Ground
  GTE: Gate
  GTES: Gates
  GTWY: Gateway
  HETH: Heath
  HILL: Hill
  HLLW: HLLW
  HRBR: HRBR
  HRD: Highroad
  HTS: Heights
  HUB: Hub
  HVN: HVN
  HWY: Highway
  INLT: INLT
  INTG: Interchange
  INTN: Intersection
  ISLD: Island
  JNC: Junction
  KEY: Key
  KEYS: KEYS
  KNOL: KNOL
  LADR: LADR
  LANE: Lane
  LDG: Landing
  LEAD: LEAD
  LEDR: LEDR
  LEES: Lees
  LINE: Line
  LINK: Link
  LKT: Lookout
  LNWY: Laneway
  LOOP: Loop
  LT: Little
  LWR: Lower
  LYNN: LYNN
  MALL: Mall
  MANR: MANR
  MART: MART
  MEAD: MEAD
  MEW: Mew
  MEWS: Mews
  MILE: MILE
  MNDR: Meander
  MT: Mount
  MWY: Motorway
  NOOK: Nook
  NTH: NTH
  NULL: NULL
  OTLK: Outlook
  OTLT: OTLT
  OVAL: OVAL
  PARK: Park
  PART: Part
  PASS: Pass
  PATH: Path
  PDE: Parade
  PHWY: Pathway
  PIAZ: Piazza
  PKLD: Parklands
  PKT: Pocket
  PKWY: Parkway
  PL: Place
  PLAT: Plateau
  PLMS: PLMS
  PLZA: Plaza
  PNT: Point
  PORT: Port
  PRDS: PRDS
  PREC: PREC
  PROM: Promenade
  PRST: Pursuit
  PSGE: Passage
  PSLA: PSLA
  QDGL: Quadrangle
  QDRT: Quadrant
  QUAD: Quad
  QY: Quay
  QYS: Quays
  RAMP: Ramp
  RCH: Reach
  RD: Road
  RDGE: Ridge
  RDS: Roads
  RDSD: Roadside
  RDWY: Roadway
  REEF: REEF
  RES: Reserve
  REST: Rest
  RGWY: Ridgeway
  RIDE: Ride
  RING: Ring
  RISE: Rise
  RMBL: Ramble
  RND: Round
  RNDE: Ronde
  RNGE: Range
  ROW: Row
  ROWE: ROWE
  ROWY: Right Of Way
  RSBL: Rosebowl
  RSNG: RSNG
  RTE: Route
  RTRN: Return
  RTT: Retreat
  RTY: Rotary
  RUE: Rue
  RUN: Run
  RVR: River
  RVRA: Riviera
  RVWY: Riverway
  SBWY: Subway
  SDNG: Siding
  SHUN: SHUN
  SHWY: State
  SKLN: SKLN
  SLPE: Slope
  SND: Sound
  SPUR: Spur
  SQ: Square
  ST: Street
  STAI: STAI
  STH: STH
  STPS: Steps
  STRA: Strand
  STRP: Strip
  STRS: Stairs
  STRT: STRT
  SVWY: SVWY
  SWY: Service
  TARN: Tarn
  TCE: Terrace
  THFR: THFR
  THOR: Thoroughfare
  THRU: THRU
  TKWY: Trunkway
  TLWY: Tollway
  TMWY: TMWY
  TOP: Top
  TOR: Tor
  TRI: Triangle
  TRK: Track
  TRL: Trail
  TRLR: Trailer
  TUNL: TUNL
  TURN: Turn
  TVSE: TVSE
  TWRS: Towers
  UPAS: Underpass
  UPR: Upper
  VALE: Vale
  VDCT: Viaduct
  VIEW: Views
  VLGE: VLGE
  VLL: VLL
  VLLA: VLLA
  VLLS: Villas
  VLLY: VLLY
  VSTA: Vista
  VUE: VUE
  VWS: VWS
  WADE: Wade
  WALK: Walk
  WAY: Way
  WDS: WDS
  WHRF: Whrf
  WKWY: Walkway
  WOOD: Wood
  WTRS: Waters
  WTWY: WTWY
  WYND: Wynd
  YARD: Yard